### ISSUE TITLE
`extra-conf` substituter is ignored

### ISSUE THREAD

**Issue by eureka-cpu** [DeterminateSystems/determinate-nix-action#16]
I just switched to the detsys action to try out lazy trees, and it would seem my substituter is no longer being applied. Here's what I have:

```yaml
name: Nix Flake Check

on:
  workflow_call:

jobs:
  nix-flake-check:
    name: Nix Flake Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            lazy-trees = true
            extra-substituters = https://cloud-scythe-labs.cachix.org
            extra-trusted-public-keys = cloud-scythe-labs.cachix.org-1:I+IM+x2gGlmNjUMZOsyHJpxIzmAi7XhZNmTVijGjsLw=

      - uses: DeterminateSystems/flake-checker-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          upstream-cache: https://cloud-scythe-labs.cachix.org

      - run: nix flake check --keep-going
```

Here is a workflow run before switching to the detsys with lazy trees: https://github.com/Cloud-Scythe-Labs/cargo-reaper/actions/runs/15788871521/job/44510969075#step:5:18
And here is after: https://github.com/Cloud-Scythe-Labs/cargo-reaper/actions/runs/15790415872/job/44515117079

This could be related to one of the issues I opened on the magic nix cache repo, where it still decides to cache things that should be coming from the substituter.

**Comment by grahamc** [comment]
Hrm.

With this workflow:

```yml
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            lazy-trees = true
            extra-substituters = https://cloud-scythe-labs.cachix.org
            extra-trusted-public-keys = cloud-scythe-labs.cachix.org-1:I+IM+x2gGlmNjUMZOsyHJpxIzmAi7XhZNmTVijGjsLw=
      - run: nix config show
```

I saw this in the config output:

```
substituters = https://cache.nixos.org/ https://cloud-scythe-labs.cachix.org/ https://cache.flakehub.com/
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cloud-scythe-labs.cachix.org-1:I+IM+x2gGlmNjUMZOsyHJpxIzmAi7XhZNmTVijGjsLw= [...]
trusted-substituters = https://cache.flakehub.com/ https://install.determinate.systems/
```

which seems correct.
